(library (srfi srfi-111)
  (export box box? unbox set-box!)
  (import (only (chezsheme) box))
  (import (only (chezsheme) box?))
  (import (only (chezsheme) unbox))
  (import (only (chezsheme) set-box!)))
