(library (scheme text)
  (export text?
          textual?
          textual-null?
          textual-every
          textual-any
          make-text
          text
          text-tabulate
          text-unfold
          text-unfold-right
          textual->text
          textual->string
          textual->vector
          textual->list
          string->text
          vector->text
          list->text
          reverse-list->text
          textual->utf8
          textual->utf16
          textual->utf16be
          textual->utf16le
          utf8->text
          utf16->text
          utf16be->text
          utf16le->text
          text-length
          text-ref
          textual-length
          textual-ref
          subtext
          subtextual
          textual-copy
          textual-take
          textual-drop
          textual-take-right
          textual-drop-right
          textual-pad
          textual-pad-right
          textual-trim
          textual-trim-right
          textual-trim-both
          textual-replace
          textual=?
          textual<?
          textual>?
          textual<=?
          textual>=?
          textual-ci=?
          textual-ci<?
          textual-ci>?
          textual-ci<=?
          textual-ci>=?
          textual-prefix-length
          textual-suffix-length
          textual-prefix?
          textual-suffix?
          textual-index
          textual-index-right
          textual-skip
          textual-skip-right
          textual-contains
          textual-contains-right
          textual-upcase
          textual-downcase
          textual-foldcase
          textual-titlecase
          textual-append
          textual-concatenate
          textual-concatenate-reverse
          textual-join
          textual-fold
          textual-fold-right
          textual-map
          textual-for-each
          textual-map-index
          textual-for-each-index
          textual-count
          textual-filter
          textual-remove
          textual-replicate
          textual-split)
  (import (srfi srfi-135)))
